from pathlib import Path
import re

rig = Path('rigorous_metrics_all.txt').read_text(encoding='utf-8', errors='ignore')
auc = re.search(r'^AUC:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
auprc = re.search(r'^AUPRC:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
f1 = re.search(r'^F1:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
acc = re.search(r'^Acc:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
brier = re.search(r'^Brier:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
ece = re.search(r'^ECE:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
sev_macro = re.search(r'^Sev_Macro_F1:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)
sev_weighted = re.search(r'^Sev_W_F1:\s*([0-9.]+)\s*\+\-\s*([0-9.]+)', rig, re.M)

trans = Path('real_metrics_output.txt').read_text(encoding='utf-16', errors='ignore')
def g(p):
    m = re.search(p, trans, re.S)
    return m.group(1) if m else 'N/A'

t_auc = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?AUC-ROC:\s*([0-9.]+)')
t_acc = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?Accuracy:\s*([0-9.]+)')
t_prec = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?Precision:\s*([0-9.]+)')
t_rec = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?Recall:\s*([0-9.]+)')
t_f1 = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?F1 Score:\s*([0-9.]+)')
t_sev = g(r'TEST SET METRICS \(FINAL PERFORMANCE\).*?Severity Accuracy:\s*([0-9.]+)')

print('\n' + '='*90)
print('IEEE METRICS (REAL RUN OUTPUT)')
print('='*90)
print('Primary Binary (Cold-Start/Inductive, mean +- std over seeds):')
print(f"AUC-ROC: {auc.group(1)} +- {auc.group(2)}")
print(f"AUPRC:   {auprc.group(1)} +- {auprc.group(2)}")
print(f"F1:      {f1.group(1)} +- {f1.group(2)}")
print(f"Accuracy:{acc.group(1)} +- {acc.group(2)}")
print('Precision: N/A in rigorous summary file (not exported)')
print('Recall:    N/A in rigorous summary file (not exported)')
print('')
print('Severity Classification (Cold-Start):')
print(f"Macro-F1:    {sev_macro.group(1)} +- {sev_macro.group(2)}")
print(f"Weighted-F1: {sev_weighted.group(1)} +- {sev_weighted.group(2)}")
print('Per-class F1: N/A (not exported in current summary file)')
print('Confusion Matrix: final_plot/severity_confusion_matrix.png')
print('')
print('Calibration (Cold-Start):')
print(f"ECE:   {ece.group(1)} +- {ece.group(2)}")
print(f"Brier: {brier.group(1)} +- {brier.group(2)}")
print('')
print('Transductive Test (single split from get_metrics.py):')
print(f"AUC-ROC: {t_auc}")
print(f"Accuracy: {t_acc}")
print(f"Precision: {t_prec}")
print(f"Recall: {t_rec}")
print(f"F1: {t_f1}")
print(f"Severity Accuracy: {t_sev}")
print('='*90)
